[phases.setup]
aptPkgs = [
  "ca-certificates",
  "fonts-liberation",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libatspi2.0-0",
  "libc6",
  "libcairo2",
  "libcups2",
  "libdbus-1-3",
  "libdrm2",
  "libexpat1",
  "libfreetype6",
  "libfontconfig1",
  "libfreetype6",
  "libharfbuzz0b",
  "libgbm1",
  "libgcc-s1",
  "libglib2.0-0",
  "chromium",
  "libnss3",
  "libatk-bridge2.0-0",
  "libx11-xcb1",
  "libxcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libgbm1",
  "libasound2"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"